name = "hoshimachi"
type = "webpack"
workers_dev = true
account_id = "1bed4e5b9ed9f9fa1788d5f4c798bdba"
zone_id = "634bf0522460e11cbaa85073023df38e"
kv_namespaces = [
    { binding = "BUCKET", id = "0bd9bb29528f4192bdae87703d619788" }
]

[env.staging]
name = "drive-staging"
